import os                          # Access environment variables (API key)
import google.generativeai as genai  # Google Gemini API library
from dotenv import load_dotenv     # Load .env file securely
from PIL import Image              # Image processing library

# ─────────────────────────────────────────────────────────────────────────────
# LOAD API KEY — Reads the Gemini API key from the .env file
# This keeps the key out of the source code (safe for GitHub)
# ─────────────────────────────────────────────────────────────────────────────
load_dotenv()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# Configure the Gemini client with the API key
genai.configure(api_key=GEMINI_API_KEY)

# Load the Gemini multimodal model — capable of analyzing both text and images
model = genai.GenerativeModel("gemini-1.5-flash")

# ─────────────────────────────────────────────────────────────────────────────
# ECG ANALYSIS PROMPT — Instructs Gemini on how to read the ECG image
# Written in Portuguese to match the clinical context of Brazilian health workers
# ─────────────────────────────────────────────────────────────────────────────
ECG_PROMPT = """
Você é um especialista em eletrocardiografia clínica.
Analise esta imagem de ECG e forneça uma interpretação estruturada seguindo
as diretrizes da Sociedade Brasileira de Cardiologia (SBC).

Avalie obrigatoriamente os seguintes itens:

1. RITMO
   - Sinusal, fibrilação atrial, flutter, taquicardia, bradicardia?
   - Frequência cardíaca estimada (bpm)

2. EIXO ELÉTRICO
   - Normal, desvio para esquerda, desvio para direita?

3. INTERVALO PR
   - Normal (120-200ms)? Prolongado? Curto?

4. COMPLEXO QRS
   - Duração normal (<120ms)? Alargado?
   - Morfologia: bloqueio de ramo esquerdo (BRE)? Bloqueio de ramo direito (BRD)?

5. SEGMENTO ST
   - Supradesnivelamento? Em quais derivações?
   - Infradesnivelamento? Em quais derivações?
   - Padrão normal?

6. ONDA T
   - Normal? Invertida? Apiculada?
   - Em quais derivações?

7. INTERVALO QT
   - Normal? Prolongado? (risco de Torsades de Pointes)

8. ACHADOS RELEVANTES
   - Sinais de isquemia aguda?
   - Sinais de IAM (infarto agudo do miocárdio)?
   - Hipertrofia ventricular?
   - Outras alterações significativas?

9. INTERPRETAÇÃO FINAL
   - 🔴 ALTERADO — URGENTE: risco imediato à vida
   - 🟡 ALTERADO — ATENÇÃO: requer avaliação médica
   - 🟢 NORMAL: sem alterações significativas

10. RECOMENDAÇÃO PARA O AGENTE DE SAÚDE
    - O que fazer AGORA com base neste ECG?

Seja claro, direto e use linguagem acessível para agentes de saúde não especialistas.
"""

# ─────────────────────────────────────────────────────────────────────────────
# ECG COMBINATION PROMPT — Merges ECG findings with symptom triage
# This is the key innovation: combining two sources of clinical data
# ─────────────────────────────────────────────────────────────────────────────
ECG_COMBINATION_PROMPT = """
Você é um cardiologista de plantão em uma Unidade Básica de Saúde brasileira.

Você recebeu dois relatórios sobre o mesmo paciente:

RELATÓRIO 1 — TRIAGEM POR SINTOMAS:
{symptom_triage}

RELATÓRIO 2 — ANÁLISE DO ECG:
{ecg_analysis}

Com base nos DOIS relatórios combinados, forneça uma recomendação clínica final:

🎯 DIAGNÓSTICO MAIS PROVÁVEL:
[Qual é a hipótese diagnóstica principal considerando sintomas + ECG?]

🔴/🟡/🟢 NÍVEL DE RISCO FINAL:
[Confirma ou altera o risco identificado na triagem por sintomas?]

✅ CONDUTA IMEDIATA:
[O que o agente de saúde deve fazer AGORA, considerando os dois relatórios?]

🏥 ENCAMINHAMENTO:
[SAMU 192 / UPA / Hospital / UBS — com qual urgência?]

⚡ ATENÇÃO ESPECIAL:
[Algo que o ECG revelou que muda ou reforça a conduta inicial?]

Seja objetivo e use linguagem simples para agentes de saúde.
"""


def analyze_ecg(image_path: str) -> str:
    """
    Sends an ECG image to Gemini for multimodal analysis.
    Returns a structured clinical interpretation in Portuguese.

    This function runs in the cloud via Gemini API —
    requires internet connection and a valid API key in .env

    Args:
        image_path: File path to the ECG image (JPG, PNG, PDF scan)

    Returns:
        Structured ECG interpretation with rhythm, ST segment,
        QRS complex and clinical recommendation for health workers
    """

    # Open the ECG image from disk
    ecg_image = Image.open(image_path)

    # Send image + clinical prompt to Gemini multimodal model
    response = model.generate_content([ECG_PROMPT, ecg_image])

    # Return the text interpretation generated by Gemini
    return response.text


def combined_analysis(symptom_triage: str, ecg_analysis: str) -> str:
    """
    Combines symptom triage output (from Gemma local) with ECG analysis
    (from Gemini cloud) into a single unified clinical recommendation.

    This is the core innovation of BeatSafe:
    two AI models working together for a more accurate triage.

    Args:
        symptom_triage: Output from the triage() function in main.py
        ecg_analysis:   Output from the analyze_ecg() function above

    Returns:
        Unified clinical recommendation combining both data sources
    """

    # Build the combination prompt with both reports filled in
    prompt = ECG_COMBINATION_PROMPT.format(
        symptom_triage=symptom_triage,
        ecg_analysis=ecg_analysis
    )

    # Send to Gemini for final unified analysis
    response = model.generate_content(prompt)

    return response.text


def full_beatsafe_analysis(patient_info: str, image_path: str) -> dict:
    """
    Runs the complete BeatSafe pipeline for a patient with an ECG image:
        1. Symptom triage via Gemma 3 local (offline)
        2. ECG image analysis via Gemini API (cloud)
        3. Combined final recommendation

    Args:
        patient_info: Patient symptoms, vitals and history (text)
        image_path:   Path to the ECG image file

    Returns:
        Dictionary with three keys:
            - symptom_triage: result from Gemma local
            - ecg_analysis:   result from Gemini multimodal
            - final:          unified combined recommendation
    """

    # Import here to avoid circular imports between ecg.py and main.py
    from main import triage

    # Step 1 — Run symptom triage using local Gemma model (offline)
    print("🫀 Step 1/3 — Running symptom triage with Gemma (local)...")
    symptom_result = triage(patient_info)

    # Step 2 — Analyze ECG image using Gemini API (cloud)
    print("📊 Step 2/3 — Analyzing ECG image with Gemini (cloud)...")
    ecg_result = analyze_ecg(image_path)

    # Step 3 — Combine both analyses into a unified recommendation
    print("🔗 Step 3/3 — Combining both analyses...")
    final_result = combined_analysis(symptom_result, ecg_result)

    # Return all three results as a structured dictionary
    return {
        "symptom_triage": symptom_result,
        "ecg_analysis": ecg_result,
        "final": final_result
    }


# ─────────────────────────────────────────────────────────────────────────────
# TEST BLOCK — Runs only when this file is executed directly
# Downloads a sample ECG from PTB-XL public dataset for testing
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":

    import urllib.request  # Download sample ECG image for testing

    print("📊 BeatSafe — ECG Multimodal Analysis Module")
    print("=" * 50)
    print("Powered by Gemini 1.5 Flash (Google AI)")
    print("=" * 50)

    # Download a sample ECG image for testing (public domain)
    sample_ecg_url = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/SinusRhythmLabels.svg/800px-SinusRhythmLabels.svg.png"
    sample_ecg_path = "sample_ecg.png"

    print("\n⬇️  Downloading sample ECG image...")
    urllib.request.urlretrieve(sample_ecg_url, sample_ecg_path)
    print(f"✅ Sample ECG saved as: {sample_ecg_path}")

    # Test patient data — same as Case 1 in main.py
    test_patient = """
    Paciente: Homem, 58 anos
    Queixa principal: Dor no peito há 2 horas, tipo aperto, com irradiação para braço esquerdo
    Sintomas associados: Falta de ar, sudorese fria, náusea
    Histórico médico: Hipertensão há 10 anos, diabetes tipo 2, ex-tabagista
    Sinais vitais: PA 165/105 mmHg, FC 102 bpm, SatO2 91%
    """

    print("\n🔬 Running full BeatSafe analysis...")
    print("-" * 50)

    # Run the complete pipeline
    results = full_beatsafe_analysis(test_patient, sample_ecg_path)

    print("\n📋 SYMPTOM TRIAGE (Gemma local):")
    print("-" * 40)
    print(results["symptom_triage"])

    print("\n📊 ECG ANALYSIS (Gemini cloud):")
    print("-" * 40)
    print(results["ecg_analysis"])

    print("\n🎯 FINAL COMBINED RECOMMENDATION:")
    print("-" * 40)
    print(results["final"])
